services:
  db:
    image: postgres:alpine3.18
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=ai_db
      - POSTGRES_PASSWORD=pwd
    volumes:
      - postgresdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 127.0.0.1:5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pwd
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    volumes:
      - ./db/servers.json:/pgadmin4/servers.json
    logging:
      driver: none

volumes:
  postgresdata:
  redisdata:
